{
 "title": "Peloton To Garmin",
 "description": "Dashboard for viewing opentel metrics from P2G",
 "tags": [
  "fitness",
  "opentelemetry",
  "logs",
  "tracing",
  "metrics",
  "guest"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "![Image](https://github.com/philosowaffle/peloton-to-garmin/raw/master/images/logo/readme_banner.png)\r\n"
   }
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_build_info" }
   ]
  },
  {
   "title": "Next Sync Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUSNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_next_sync_time * 1000", "legendFormat": "Next Sync Time" }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_build_info" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"p2g\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Avg. Sync Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2g_sync_duration_seconds_sum / p2g_sync_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Total Polls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2g_sync_duration_seconds_count"
    }
   ]
  },
  {
   "title": "DotNet Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_build_info" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_health_info" }
   ]
  },
  {
   "type": "gauge",
   "description": "Failed Upload Attempts",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_failed_upload_attempts", "legendFormat": "Failed Upload Attempts" }
   ]
  },
  {
   "type": "gauge",
   "description": "Files to Upload",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2g_files_to_upload", "legendFormat": "Files to Upload" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"p2g\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({app=\"p2g\"} | json [30m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(increase(docker_container_cpu_used_total{job = \"homeservices-docker\", name = \"p2g\"}[30s]) / increase(docker_container_cpu_capacity_total[30s])) > 0 \nor (increase(docker_container_cpu_used_total{job = \"homeservices-docker\", name = \"p2g\"}[1m]) / increase(docker_container_cpu_capacity_total[1m])) > 0 \nor (increase(docker_container_cpu_used_total{job = \"homeservices-docker\", name = \"p2g\"}[3m]) / increase(docker_container_cpu_capacity_total[3m])) > 0 \nor (increase(docker_container_cpu_used_total{job = \"homeservices-docker\", name = \"p2g\"}[5m]) / increase(docker_container_cpu_capacity_total[5m]))",
     "legendFormat": "System CPU"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"p2g\"}[$__interval])",
     "legendFormat": "Container CPU"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "{app=\"p2g\"} | json",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk I/O bytes/second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "-irate(docker_container_disk_read_bytes{name=\"p2g\", job=\"homeservices-docker\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "irate(docker_container_disk_write_bytes{name=\"p2g\", job=\"homeservices-docker\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"p2g\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(docker_container_network_in_bytes{job=\"homeservices-docker\",name=\"p2g\"}[$__rate_interval]) * -1",
     "legendFormat": "Download"
    },
    {
     "expr": "irate(docker_container_network_out_bytes{job=\"homeservices-docker\",name=\"p2g\"}[$__rate_interval])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Github",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Issues",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "targets": [
      { "options": { "query": "is:issue is:open ", "timeField": 0 }, "owner": "philosowaffle", "repository": "peloton-to-garmin" }
     ]
    },
    {
     "title": "Open PRs",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "targets": [
      { "options": { "gitRef": "v2", "query": " is:open ", "timeField": 1 }, "owner": "philosowaffle", "repository": "peloton-to-garmin" }
     ]
    }
   ]
  },
  {
   "title": "DotNet Process Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "dotnet_total_memory_bytes{job=\"p2g\"}",
       "legendFormat": "DotNet Total Memory Bytes"
      },
      {
       "expr": "process_working_set_bytes{job=\"p2g\"}",
       "legendFormat": "Process Working Set (RAM)"
      },
      {
       "expr": "process_private_memory_bytes{job=\"p2g\"}",
       "legendFormat": "Process Private Memory Bytes"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"p2g\"}",
       "legendFormat": "Process Virtual Memory Bytes"
      }
     ]
    },
    {
     "title": "Open Handles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(process_open_handles{job=\"p2g\"}[$__interval])",
       "legendFormat": "Memory in Use"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"p2g\"}[$__interval])",
       "legendFormat": "CPU Process Secodns"
      }
     ]
    },
    {
     "title": "Num Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(process_num_threads{job=\"p2g\"}[$__interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"p2g\"}"
      }
     ]
    },
    {
     "title": "Samples Scraped",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 3, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scrape_samples_scraped{job=\"p2g\"}"
      }
     ]
    },
    {
     "title": "Scrape Duration Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(scrape_duration_seconds{job=\"p2g\"}[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O bytes/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(docker_container_disk_read_bytes{name=\"p2g\", job=\"homeservices-docker\"}[$__rate_interval])",
       "legendFormat": "Read"
      },
      {
       "expr": "irate(docker_container_disk_write_bytes{name=\"p2g\", job=\"homeservices-docker\"}[$__rate_interval])",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  }
 ]
}